FROM golang:1.24-alpine as builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=1 go build -o migrator ./cmd/migrator

FROM alpine:latest
WORKDIR /root/
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/migrator .
COPY ./migrations ./migrations
RUN mkdir -p /root/storage
CMD ["./migrator", "--storage-path=./storage/sso.db", "--migrations-path=./migrations"]
